### ISSUE TITLE
What about using plugins.txt with the official jenkins plugins.sh?

### ISSUE THREAD

**Issue by emdem** [pitchplay/jenkins-docker-volume#3]
The official jenkins docker image includes a plugins.sh script that can be used as such:
ADD plugins.txt /usr/share/jenkins/ref/
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt

Where plugins.txt is a file formatted like so (new line for each plugin):
 plugin_name:plugin_version

**Comment by Lykathia** [comment]
Interesting.

I wasn't expecting the official jenkins image to have python installed on it as well. I'm presuming there is going to be more default configuration needed for ease of use w/ spinning slaves up and down.

However could drop the need for python and use a smaller image w/ a script like that ... assuming the other config can be done in a similar manner as well.

**Comment by Lykathia** [comment]
Looks as tho both this current solution and the plugins.sh script both have a failure in dependency resolution.

Going to do some more testing w/ it later tonight, and if that is the case I'll close this and add a ticket for extending the plugin system to fetch dependencies.

**Comment by Lykathia** [comment]
Closing this, as #4 will provide enough of an advantage over the image plugin scripts.
